// Package soceng: social-engineering password dictionary generator.
// 完整姓氏表(467) + 常用名(75) + 名用字拼音(88)——不做精简。
package soceng

import (
	"fmt"
	"strings"
)

// surnames: 完整姓氏拼音表（467 个，含复姓）
var surnames = map[string]string{
	"丁": "ding",
	"万": "wan",
	"万俟": "moqi",
	"上官": "shangguan",
	"丛": "cong",
	"东": "dong",
	"东方": "dongfang",
	"东门": "dongmen",
	"严": "yan",
	"丰": "feng",
	"乌": "wu",
	"乐": "le",
	"乔": "qiao",
	"乜": "nie",
	"习": "xi",
	"于": "yu",
	"云": "yun",
	"井": "jing",
	"亢": "kang",
	"仇": "qiu",
	"从": "cong",
	"令狐": "linghu",
	"仰": "yang",
	"仲": "zhong",
	"仲孙": "zhongsun",
	"任": "ren",
	"伊": "yi",
	"伍": "wu",
	"伏": "fu",
	"伯": "bo",
	"何": "he",
	"佘": "she",
	"余": "yu",
	"佟": "tong",
	"佴": "nai",
	"侯": "hou",
	"俞": "yu",
	"倪": "ni",
	"傅": "fu",
	"储": "chu",
	"元": "yuan",
	"充": "chong",
	"党": "dang",
	"全": "quan",
	"公": "gong",
	"公冶": "gongye",
	"公孙": "gongsun",
	"公羊": "gongyang",
	"关": "guan",
	"养": "yang",
	"冀": "ji",
	"冉": "ran",
	"农": "nong",
	"冯": "feng",
	"况": "kuang",
	"冷": "leng",
	"凌": "ling",
	"凤": "feng",
	"刁": "diao",
	"刘": "liu",
	"利": "li",
	"别": "bie",
	"劳": "lao",
	"勾": "gou",
	"包": "bao",
	"匡": "kuang",
	"华": "hua",
	"卓": "zhuo",
	"单": "shan",
	"单于": "chanyu",
	"南宫": "nangong",
	"卜": "bu",
	"卞": "bian",
	"卢": "lu",
	"卫": "wei",
	"印": "yin",
	"危": "wei",
	"厉": "li",
	"厍": "she",
	"双": "shuang",
	"古": "gu",
	"召": "shao",
	"史": "shi",
	"叶": "ye",
	"叶赫那拉": "yehenala",
	"司": "si",
	"司徒": "situ",
	"司空": "sikong",
	"吉": "ji",
	"后": "hou",
	"向": "xiang",
	"吕": "lv",
	"吴": "wu",
	"周": "zhou",
	"和": "he",
	"咸": "xian",
	"哈": "ha",
	"唐": "tang",
	"商": "shang",
	"喻": "yu",
	"国": "guo",
	"堵": "du",
	"墨": "mo",
	"夏": "xia",
	"夏侯": "xiahou",
	"夔": "kui",
	"太叔": "taishu",
	"奚": "xi",
	"姚": "yao",
	"姜": "jiang",
	"姬": "ji",
	"娄": "lou",
	"孔": "kong",
	"孙": "sun",
	"孟": "meng",
	"季": "ji",
	"宁": "ning",
	"宇文": "yuwen",
	"安": "an",
	"宋": "song",
	"宓": "mi",
	"宗": "zong",
	"宗政": "zongzheng",
	"宣": "xuan",
	"宦": "huan",
	"宫": "gong",
	"宰": "zai",
	"家": "jia",
	"容": "rong",
	"宿": "su",
	"寇": "kou",
	"富": "fu",
	"寿": "shou",
	"封": "feng",
	"尉迟": "yuchi",
	"尚": "shang",
	"尤": "you",
	"尹": "yin",
	"居": "ju",
	"屈": "qu",
	"屠": "tu",
	"山": "shan",
	"岑": "cen",
	"岳": "yue",
	"崔": "cui",
	"嵇": "ji",
	"巢": "chao",
	"左": "zuo",
	"左丘": "zuoqiu",
	"巩": "gong",
	"巫": "wu",
	"巴": "ba",
	"帅": "shuai",
	"师": "shi",
	"席": "xi",
	"常": "chang",
	"干": "gan",
	"平": "ping",
	"年": "nian",
	"幸": "xing",
	"广": "guang",
	"庄": "zhuang",
	"应": "ying",
	"庞": "pang",
	"康": "kang",
	"庾": "yu",
	"廉": "lian",
	"廖": "liao",
	"弓": "gong",
	"弘": "hong",
	"张": "zhang",
	"强": "qiang",
	"彭": "peng",
	"徐": "xu",
	"怀": "huai",
	"惠": "hui",
	"慎": "shen",
	"慕": "mu",
	"慕容": "murong",
	"戈": "ge",
	"戎": "rong",
	"成": "cheng",
	"戚": "qi",
	"戴": "dai",
	"房": "fang",
	"扈": "hu",
	"扶": "fu",
	"支": "zhi",
	"敖": "ao",
	"文": "wen",
	"方": "fang",
	"於": "yu",
	"施": "shi",
	"时": "shi",
	"昌": "chang",
	"明": "ming",
	"易": "yi",
	"昝": "zan",
	"晁": "chao",
	"晏": "yan",
	"景": "jing",
	"暨": "ji",
	"暴": "bao",
	"曲": "qu",
	"曹": "cao",
	"曾": "zeng",
	"有": "you",
	"朱": "zhu",
	"权": "quan",
	"李": "li",
	"杜": "du",
	"束": "shu",
	"杨": "yang",
	"杭": "hang",
	"松": "song",
	"林": "lin",
	"柏": "bai",
	"查": "zha",
	"柯": "ke",
	"柳": "liu",
	"柴": "chai",
	"栾": "luan",
	"桂": "gui",
	"桑": "sang",
	"桓": "huan",
	"梁": "liang",
	"梁丘": "liangqiu",
	"梅": "mei",
	"樊": "fan",
	"欧": "ou",
	"欧阳": "ouyang",
	"步": "bu",
	"武": "wu",
	"殳": "shu",
	"段": "duan",
	"殷": "yin",
	"毋": "wu",
	"毕": "bi",
	"毛": "mao",
	"水": "shui",
	"江": "jiang",
	"池": "chi",
	"汤": "tang",
	"汪": "wang",
	"汲": "ji",
	"沃": "wo",
	"沈": "shen",
	"沙": "sha",
	"洪": "hong",
	"浦": "pu",
	"淳于": "chunyu",
	"温": "wen",
	"游": "you",
	"湛": "zhan",
	"滕": "teng",
	"满": "man",
	"潘": "pan",
	"澹台": "tantai",
	"濮": "pu",
	"濮阳": "puyang",
	"焦": "jiao",
	"熊": "xiong",
	"燕": "yan",
	"爱": "ai",
	"牛": "niu",
	"牟": "mou",
	"牧": "mu",
	"狄": "di",
	"王": "wang",
	"班": "ban",
	"琴": "qin",
	"璩": "qu",
	"甄": "zhen",
	"甘": "gan",
	"田": "tian",
	"申": "shen",
	"申屠": "shentu",
	"白": "bai",
	"皇甫": "huangfu",
	"皮": "pi",
	"益": "yi",
	"盖": "gai",
	"盛": "sheng",
	"相": "xiang",
	"瞿": "qu",
	"石": "shi",
	"祁": "qi",
	"祖": "zu",
	"祝": "zhu",
	"禄": "lu",
	"福": "fu",
	"禹": "yu",
	"秋": "qiu",
	"秦": "qin",
	"程": "cheng",
	"穆": "mu",
	"空": "kong",
	"窦": "dou",
	"章": "zhang",
	"童": "tong",
	"竺": "zhu",
	"符": "fu",
	"笪": "da",
	"第五": "diwu",
	"简": "jian",
	"管": "guan",
	"籍": "ji",
	"米": "mi",
	"糜": "mi",
	"索": "suo",
	"红": "hong",
	"纪": "ji",
	"终": "zhong",
	"经": "jing",
	"缑": "gou",
	"缪": "miao",
	"罗": "luo",
	"羊": "yang",
	"羿": "yi",
	"翁": "weng",
	"翟": "zhai",
	"耿": "geng",
	"聂": "nie",
	"胡": "hu",
	"胥": "xu",
	"能": "neng",
	"臧": "zang",
	"舒": "shu",
	"舜": "shun",
	"艾": "ai",
	"芮": "rui",
	"花": "hua",
	"苍": "cang",
	"苏": "su",
	"苗": "miao",
	"范": "fan",
	"茅": "mao",
	"茹": "ru",
	"荀": "xun",
	"荆": "jing",
	"荣": "rong",
	"莘": "shen",
	"莫": "mo",
	"萧": "xiao",
	"葛": "ge",
	"董": "dong",
	"蒋": "jiang",
	"蒙": "meng",
	"蒯": "kuai",
	"蒲": "pu",
	"蓝": "lan",
	"蓟": "ji",
	"蓬": "peng",
	"蔚": "wei",
	"蔡": "cai",
	"蔺": "lin",
	"薄": "bo",
	"薛": "xue",
	"虞": "yu",
	"融": "rong",
	"衡": "heng",
	"袁": "yuan",
	"裘": "qiu",
	"裴": "pei",
	"褚": "chu",
	"西门": "ximen",
	"解": "xie",
	"言": "yan",
	"訾": "zi",
	"詹": "zhan",
	"计": "ji",
	"许": "xu",
	"诸": "zhu",
	"诸葛": "zhuge",
	"谈": "tan",
	"谢": "xie",
	"谭": "tan",
	"谯": "qiao",
	"谷": "gu",
	"贝": "bei",
	"贡": "gong",
	"贲": "ben",
	"费": "fei",
	"贺": "he",
	"贾": "jia",
	"赏": "shang",
	"赖": "lai",
	"赫连": "helian",
	"赵": "zhao",
	"越": "yue",
	"路": "lu",
	"车": "che",
	"轩辕": "xuanyuan",
	"辛": "xin",
	"边": "bian",
	"连": "lian",
	"逄": "pang",
	"通": "tong",
	"逯": "lu",
	"邓": "deng",
	"邢": "xing",
	"那": "na",
	"邬": "wu",
	"邰": "tai",
	"邱": "qiu",
	"邴": "bing",
	"邵": "shao",
	"邹": "zou",
	"郁": "yu",
	"郎": "lang",
	"郏": "jia",
	"郑": "zheng",
	"郗": "xi",
	"郜": "gao",
	"郝": "hao",
	"郤": "xi",
	"郦": "li",
	"郭": "guo",
	"都": "du",
	"鄂": "e",
	"酆": "feng",
	"金": "jin",
	"钟": "zhong",
	"钟离": "zhongli",
	"钭": "tou",
	"钱": "qian",
	"长孙": "zhangsun",
	"闵": "min",
	"闻": "wen",
	"闻人": "wenren",
	"阎": "yan",
	"阙": "que",
	"阚": "kan",
	"阮": "ruan",
	"阳": "yang",
	"阴": "yin",
	"陆": "lu",
	"陈": "chen",
	"陶": "tao",
	"隆": "long",
	"隗": "wei",
	"雍": "yong",
	"雷": "lei",
	"霍": "huo",
	"靳": "jin",
	"鞠": "ju",
	"韦": "wei",
	"韩": "han",
	"韶": "shao",
	"项": "xiang",
	"须": "xu",
	"顾": "gu",
	"颜": "yan",
	"饶": "rao",
	"马": "ma",
	"骆": "luo",
	"高": "gao",
	"魏": "wei",
	"鱼": "yu",
	"鲁": "lu",
	"鲍": "bao",
	"麻": "ma",
	"黄": "huang",
	"黎": "li",
	"齐": "qi",
	"龙": "long",
	"龚": "gong",
}

// commonGiven: 常用名拼音（75 个）
var commonGiven = []string{
		"wei",
		"min",
		"juan",
		"yan",
		"fang",
		"jing",
		"lei",
		"li",
		"hong",
		"xiao",
		"yang",
		"jun",
		"qiang",
		"hua",
		"ping",
		"xia",
		"na",
		"qin",
		"chen",
		"lin",
		"liang",
		"fei",
		"dan",
		"wen",
		"chao",
		"tao",
		"peng",
		"yu",
		"jie",
		"hao",
		"gang",
		"wei",
		"bin",
		"shuai",
		"cong",
		"ning",
		"qing",
		"zhao",
		"kun",
		"shuang",
		"lu",
		"jie",
		"yan",
		"bo",
		"chun",
		"mei",
		"ling",
		"zhen",
		"xin",
		"ting",
		"shuang",
		"meng",
		"rui",
		"xiang",
		"ke",
		"si",
		"yu",
		"zhi",
		"wei",
		"an",
		"song",
		"yu",
		"chen",
		"jie",
		"ying",
		"xue",
		"lei",
		"dan",
		"hao",
		"jun",
		"hang",
		"yi",
		"cheng",
		"yi",
		"zhuo",
}

// givenMap: 名用字拼音（88 个）
var givenMap = map[string]string{
	"丹": "dan",
	"丽": "li",
	"亮": "liang",
	"伟": "wei",
	"依": "yi",
	"兰": "lan",
	"军": "jun",
	"凤": "feng",
	"刚": "gang",
	"华": "hua",
	"卓": "zhuo",
	"双": "shuang",
	"坤": "kun",
	"娜": "na",
	"娟": "juan",
	"婷": "ting",
	"宁": "ning",
	"宇": "yu",
	"安": "an",
	"宸": "chen",
	"帅": "shuai",
	"平": "ping",
	"强": "qiang",
	"彬": "bin",
	"志": "zhi",
	"思": "si",
	"悦": "yue",
	"惠": "hui",
	"成": "cheng",
	"敏": "min",
	"文": "wen",
	"春": "chun",
	"昭": "zhao",
	"晓": "xiao",
	"晨": "chen",
	"晴": "qing",
	"杰": "jie",
	"松": "song",
	"梅": "mei",
	"梦": "meng",
	"欣": "xin",
	"毅": "yi",
	"波": "bo",
	"泽": "ze",
	"洁": "jie",
	"浩": "hao",
	"涛": "tao",
	"涵": "han",
	"淑": "shu",
	"燕": "yan",
	"玉": "yu",
	"玲": "ling",
	"珂": "ke",
	"珊": "shan",
	"珍": "zhen",
	"琳": "lin",
	"琴": "qin",
	"瑞": "rui",
	"璐": "lu",
	"皓": "hao",
	"磊": "lei",
	"祥": "xiang",
	"秀": "xiu",
	"红": "hong",
	"聪": "cong",
	"航": "hang",
	"艳": "yan",
	"花": "hua",
	"芳": "fang",
	"芸": "yun",
	"英": "ying",
	"莉": "li",
	"菲": "fei",
	"蓉": "rong",
	"蕾": "lei",
	"超": "chao",
	"阳": "yang",
	"雨": "yu",
	"雪": "xue",
	"霞": "xia",
	"青": "qing",
	"静": "jing",
	"韵": "yun",
	"颖": "ying",
	"飞": "fei",
	"香": "xiang",
	"骏": "jun",
	"鹏": "peng",
}

// Generate: 生成社工字典（姓名+公司+域名+生日+邮箱全量组合）
func Generate(name, company, domain, birthday, email string) []string {
	cands := map[string]bool{}

	base := []string{"123456", "12345678", "123456789", "1234567890", "123123", "111111",
		"888888", "666666", "000000", "5201314", "qwe123", "qweasd", "asd123",
		"abc123", "a123456", "Aa123456", "Admin123", "Password1", "P@ssw0rd",
		"admin123", "admin@123", "Admin@123", "admin888"}
	for _, b := range base {
		cands[b] = true
	}

	var pinyins []string
	runes := []rune(name)
	if len(runes) >= 2 {
		if len(runes) >= 3 {
			if py, ok := surnames[string(runes[0:2])]; ok {
				pinyins = append(pinyins, py)
				runes = runes[2:]
			}
		}
		if len(pinyins) == 0 {
			if py, ok := surnames[string(runes[0])]; ok {
				pinyins = append(pinyins, py)
			} else {
				pinyins = append(pinyins, string(runes[0]))
			}
			runes = runes[1:]
		}
		for _, r := range runes {
			if py, ok := givenMap[string(r)]; ok {
				pinyins = append(pinyins, py)
			}
		}
	}
	var fullPy, initials string
	if len(pinyins) >= 2 {
		fullPy = pinyins[0] + pinyins[1]
		initials = string(pinyins[0][0]) + string(pinyins[1][0])
	}
	if fullPy != "" {
		cands[fullPy] = true
		cands[strings.ToUpper(fullPy[:1])+fullPy[1:]] = true
	}
	if initials != "" {
		cands[initials] = true
	}

	var roots []string
	if company != "" {
		roots = append(roots, strings.ToLower(company))
	}
	if domain != "" {
		roots = append(roots, strings.Split(domain, ".")[0])
	}
	if email != "" {
		if local := strings.Split(email, "@")[0]; local != "" {
			roots = append(roots, strings.ToLower(local))
		}
	}

	years := []string{"2024", "2025", "2026", "2023", "2022", "2021", "2020",
		"1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999",
		"2000", "2001", "2002", "2003", "2004", "2005", "1989", "1988", "1987", "1986", "1985", "1980"}
	for _, y := range years {
		for _, base2 := range []string{fullPy, initials} {
			if base2 != "" {
				cands[base2+y] = true
				cands[base2+"@"+y] = true
				cands[y+base2] = true
			}
		}
		for _, r := range roots {
			cands[r+y] = true
			cands[r+"@"+y] = true
			cands[r+y+"!"] = true
			cands[r+"@"+y+"!"] = true
		}
	}

	if len(birthday) >= 8 {
		ymd := strings.ReplaceAll(strings.ReplaceAll(birthday, "-", ""), "/", "")
		cands[ymd] = true
		for _, base2 := range []string{fullPy, initials} {
			if base2 != "" {
				cands[base2+ymd] = true
				cands[base2+"@"+ymd] = true
			}
		}
	}

	for _, r := range roots {
		for _, suffix := range []string{"123", "1234", "123456", "888", "666"} {
			cands[r+suffix] = true
			cands[r+"@"+suffix] = true
		}
	}

	out := make([]string, 0, len(cands))
	for c := range cands {
		if len(c) >= 6 {
			out = append(out, c)
		}
	}
	return out
}

// Format: 渲染
func Format(passwords []string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("[soceng] %d passwords generated\n", len(passwords)))
	for i, p := range passwords {
		if i < 20 {
			sb.WriteString("  " + p + "\n")
		}
	}
	return sb.String()
}
